trigger:
  - main

name: Deploy Bicep files

variables:
  vmImageName: "ubuntu-latest"

  azureServiceConnection: "Default-Service-Connection"
  resourceGroupName: "cosmos-outbox-rg"
  location: "West US 2"
  templateFile: "./cosmos.bicep"
pool:
  vmImage: $(vmImageName)

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: "$(azureServiceConnection)"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(resourceGroupName)"
      location: "$(location)"
      templateLocation: "Linked artifact"
      csmFile: "$(templateFile)"
      overrideParameters: ""
      deploymentMode: "Incremental"
      deploymentName: "DeployPipelineTemplate"
